# /***********************************************************************#
# * @file    Makefile                                                     #
# * @brief   sub Makefile file                                            #
# * @history                                                              #
# * Date       Version Author    description                              #
# * ========== ======= ========= =========================================#
# * 2018-07-06 V1.0    weihui.jia   Create                                #
# *                                                                       #
# * @Copyright (C)  2018  dixin.Co.Ltd all right reserved                 #
#************************************************************************/#
# /*@{*/

obj-y += test.o
